CREATE TABLE holes
(
CourseID int UNSIGNED NOT NULL,
HoleID int UNSIGNED NOT NULL,
HoleName VARCHAR(40) NOT NULL,
Par int UNSIGNED NOT NULL,
Hole_lat REAL NOT NULL,
Hole_lng REAL NOT NULL,
Tee_lat REAL NOT NULL,
Tee_lng REAL NOT NULL,
Zoom int NOT NULL
);