CREATE TABLE courses
(
CID int NOT NULL,
Course_Name VARCHAR(40) NOT NULL,
HID int NOT NULL,
Hole_Name VARCHAR(40) NOT NULL,
Par int NOT NULL,
Hole_lat REAL NOT NULL,
Hole_lng REAL NOT NULL,
Tee_lat REAL NOT NULL,
Tee_lng REAL NOT NULL,
Zoom int NOT NULL
);

